### ISSUE TITLE
Create new CSV file

### ISSUE THREAD

**Issue by mobilestar0223** [Nero5023/CSVParser#4]
Hello
Please let me know how to create new csv file.
Thanks.

**Comment by Nero5023** [comment]
HI!

Do you mean creating a csv file in code?
Actually this is a parser for csv file, not a specify a function to create csv file.
But you can try this for now
```swift
let csv = try! CSVParser(content: "")
csv[0] = ["col0", "col1"]                    // the element you want to write to csv file
do {
    try csv.wirite(toFilePath: "{PATH}")  // the "{Path}" is the path you want to save the csv file.
}catch let error {
    print(error)
}
```
I will add a new function to implement your requirement in next version.
If you have any questions, please let me know. Your questions will let us make this project better.
Thanks a lot.

**Comment by Nero5023** [comment]
HI,

I have add the new init methods that you can init from `[[String]]`.
This is the example:
```swift
let csv = try CSVParser(elements: [["a", "b", "c"], ["1", "2", "3"]])
```
