### ISSUE TITLE
Can't form a Character from an empty String

### ISSUE THREAD

**Issue by codesman** [Nero5023/CSVParser#5]
Hi there!

I'm trying to initialize a CSVParser from a String and I'm getting a fatal error.

Line 29 of `parser.swift` is `if inputContents[cursor] == quotes {`

This line is throwing `fatal error: Can't form a Character from an empty String`

`inputContents[cursor]` and `quotes` are both equal to a single `"` and I've tried several things trying to debug this but got nowhere.

This is the string I'm passing to the initializer with `let csvParser = try CSVParser(content: csvString)` is:
```TEXT
"Subject 1 #hashtagone","http://example.com/one"
"Subject 2 #hashtagtwo","http://example.com/two"
"Subject 3 #hashtagthree","http://example.com/three"
```

Any ideas?

**Comment by Nero5023** [comment]
Hi, 

Right now, I fix this bug. The reason is that it came across the end of string.

Thanks a lot for telling me where is wrong.
If you have any questions, please let me know. Your questions will let us make this project better.

Thanks a lot

**Comment by codesman** [comment]
Thanks, it's working!  I've noticed a couple other things that I will create issues for.
