### ISSUE TITLE
";" delimiter... crash ?

### ISSUE THREAD

**Issue by El-Fitz** [Nero5023/CSVParser#8]
Hi !

So, excel being excel, it exports utf-8 csv using semi-columns (;) characters as delimiters, and \r as line separators.

So I specified those as such... and running crashes the program in Xcode, hitting a breakpoint in the CFHash thread, before stopping with

> Message from debugger: Terminated due to signal 9

I don't have any breakpoint in my code, and CSVParser is the only framework I'm using.
Any idea ?

Just in case, here's my function

        func importCSV(filePath: String) {
		do {
			let delimeter: Character = ";"
			let lineSeparator: Character = "\r"
			let csv = try CSVParser(filePath: filePath, delimiter: delimeter, lineSeparator: lineSeparator)
			var i = 0
			for row in csv {
				print("Row \(i): \(row)\n") // ["first column", "sceond column", "third column"]
				i += 1
			}
			do {
				let jsonStr = try csv.toJSON()
				consoleIO.writeMessage("json: \(jsonStr)")
			} catch let csvToJsonError {
				consoleIO.writeMessage(csvToJsonError.localizedDescription, to: .error)
			}
		} catch let error {
			print(error)
			consoleIO.writeMessage(error.localizedDescription, to: .error)
		}
	    }

Using a random character as delimiter (such as "j") makes it work just fine... almost.

csv.toJSON() fails on the enumeratedWithDic() function, but I guess it's because there aren't any headers (since "j" isn't really a delimiter in the csv file ^^")

**Comment by El-Fitz** [comment]
Ok, so I don't know why, but the \" characters in my .csv where somehow responsible for the crash. It's weird, I don't get it, but it's solved and had nothing to do with you.

Thanks for the library, by the way ! :-)

**Comment by Nero5023** [comment]
Sorry for not replying you immediately.
Could you give me your csv file to parse. So that I can fix it.

Thanks a lot to tell me the bugs!

Also in your code you can use this.
```swift
for (index, row) in csv.enumerated() {
    print("Row \(index): \(row)\n")
}
```

**Comment by El-Fitz** [comment]
Hi ! Sorry not coming back earlier; it was one hell of a rush and I completely forgot about opening this issue when we got it working. And I don't have the .csv anymore.

But, just for future reference, the issue had to do with how we exported the file from excel (don't quite recall the details) and not the framework.

Have a great day !
